services:
  api:
    build: .  # To show where is Dockerfile
    # {container_name} will rewrite the name of the service, we don't need that
    restart: always 
    # {depends_on} only waits until {crm_db} container to get started, not till database to be completely set up, so we don't need it
    # depends_on: # avval kadom qismash korkadanasha mefahmonad
      # - crm_db
    #  we won't depend on container start, we depend on already running container condition healthy or not.
    depends_on:
      database:
        condition: service_healthy
    
    env_file:
      - .env
    # when we have {.env} file, we don't need to specify each env_var
    # environment:
    #   ASYNC_DATABASE_URL: ${ASYNC_DATABASE_URL}
    #   SYNC_DATABASE_URL: ${SYNC_DATABASE_URL}
    #   PYTHONPATH: /app    # main folder will be mounted at /app 
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app        # mount your new code as /app
      - ./app/uploads:/crm/app/uploads


  database:
    image: postgres:16.11-bookworm
    restart: always
    # when we have {.env} file, we don't need to specify each env_var
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: 1
    #   POSTGRES_DB: crm_db
    env_file:
      - .env.local
    ports:
      - "5434:5432"
    volumes:
      - crm_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  crm_data: