"""order_pro added pro_fk for creating

Revision ID: 03dad38a9794
Revises: e0f8dc5a72f4
Create Date: 2026-01-27 12:54:14.013590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03dad38a9794'
down_revision: Union[str, Sequence[str], None] = 'e0f8dc5a72f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_products', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.drop_column('order_products', 'product_id')
    # ### end Alembic commands ###
