"""init

Revision ID: 2daf8872b736
Revises: a6c95cb68eb4
Create Date: 2025-11-14 02:01:52.000694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2daf8872b736'
down_revision: Union[str, Sequence[str], None] = 'a6c95cb68eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('base_price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('sell_price', sa.Float(), nullable=False))
    op.drop_column('products', 'sell_prace')
    op.drop_column('products', 'base_prace')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('base_prace', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('sell_prace', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('products', 'sell_price')
    op.drop_column('products', 'base_price')
    # ### end Alembic commands ###
