"""init

Revision ID: 7a910daa75ce
Revises: dcb937aca8bc
Create Date: 2026-04-06 23:40:49.899002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a910daa75ce'
down_revision: Union[str, Sequence[str], None] = 'dcb937aca8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_on', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'delivery_deadline')
    op.drop_column('orders', 'is_prepaid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('is_prepaid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('delivery_deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'delivery_on')
    # ### end Alembic commands ###
