"""user model

Revision ID: 8d0bb4b74379
Revises: 7fd046547cd2
Create Date: 2025-12-17 07:21:20.251679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0bb4b74379'
down_revision: Union[str, Sequence[str], None] = '7fd046547cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'phone')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('clients', sa.Column('phone', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('address', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
