"""init

Revision ID: 9da07ef9a483
Revises: 20a3252af617
Create Date: 2025-10-22 22:04:47.501401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da07ef9a483'
down_revision: Union[str, Sequence[str], None] = '20a3252af617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_products', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_products', type_='foreignkey')
    op.drop_column('order_products', 'order_id')
    # ### end Alembic commands ###
