"""init

Revision ID: a6c95cb68eb4
Revises: 5536b12dc859
Create Date: 2025-11-14 01:52:58.159891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c95cb68eb4'
down_revision: Union[str, Sequence[str], None] = '5536b12dc859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('total_quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('active_quantity', sa.Integer(), nullable=False))
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'active_quantity')
    op.drop_column('products', 'total_quantity')
    # ### end Alembic commands ###
