"""wp p ondelete

Revision ID: d5160ecb1c49
Revises: 2daf8872b736
Create Date: 2025-11-24 21:32:03.865685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5160ecb1c49'
down_revision: Union[str, Sequence[str], None] = '2daf8872b736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('warehouse_products_product_id_fkey'), 'warehouse_products', type_='foreignkey')
    op.create_foreign_key(None, 'warehouse_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_products', type_='foreignkey')
    op.create_foreign_key(op.f('warehouse_products_product_id_fkey'), 'warehouse_products', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
